stages:
- build

build:ios:release:
  stage: build
  tags:
    - ios
  script:
    - yarn install
    - cd ./iosDemo
    - ./update.sh
    - fastlane IncreaseBuildNumberLane
    - fastlane AppCenterLane
  after_script:
    - git remote set-url origin git@gitlab.com:bct-taipei/dropthought-sdk.git
    - git add iosDemo/iosDemoObjc.xcodeproj/project.pbxproj
    - git commit -m "[ci skip] Update build number"
    - git checkout .
    - git pull origin master --rebase
    - git push origin HEAD:master
  cache:
    key: ${CI_COMMIT_REF_SLUG}-ios
    paths:
      - ./node_modules/
      - ./iosDemo/Pods/
  only:
    - master
