/** @type {import('@dropthought/dropthought-data').Survey} */
export const singlePageSurvey = {
    anonymous: true,
    kiosk: 0,
    language: 'en',
    languages: ['en'],
    pageOrder: ['c948fa69-65b6-4fd0-8611-f7d57d50b86d'],
    pages: [
        {
            pageId: 'c948fa69-65b6-4fd0-8611-f7d57d50b86d',
            pageTitle: '1st Page',
            questions: [
                {
                    category: 'Performant',
                    mandatory: false,
                    metaDataType: null,
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: '608f85e9-cd65-4534-ad73-cc02a9769768',
                    questionTitle:
                        'How Does The App Run After Installation Or Update? (Performant)',
                    scale: '5',
                    subType: 'slider',
                    type: 'rating',
                },
                {
                    category: 'Satisfaction',
                    mandatory: false,
                    metaDataType: null,
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: 'b42cc374-7fcc-43ad-9397-faad909de6f2',
                    questionTitle: 'How Useful Is The App For You?',
                    scale: '5',
                    subType: 'smiley',
                    type: 'rating',
                },
                {
                    category: 'Satisfaction',
                    mandatory: false,
                    metaDataType: null,
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: '6a36c003-b520-4504-9265-5dd9f1b4bc9d',
                    questionTitle:
                        'How Satisfied Are You With The Look And Feel Of The App?',
                    scale: '5',
                    subType: 'smiley',
                    type: 'rating',
                },
                {
                    category: 'Price',
                    mandatory: false,
                    metaDataType: null,
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: '2ce26b18-3ed8-4885-be24-2457e6316544',
                    questionTitle:
                        'How Does The Pricing Of The App Compare With Other Software In The Category?',
                    scale: '5',
                    subType: 'slider',
                    type: 'rating',
                },
                {
                    category: 'Satisfaction',
                    mandatory: false,
                    metaDataType: null,
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: 'a60acc8f-2fc6-4b05-ac44-9f5a41065dc8',
                    questionTitle:
                        'How Satisfied Are You With The Customer Support Team For The App?',
                    scale: '5',
                    subType: 'smiley',
                    type: 'rating',
                },
                {
                    mandatory: false,
                    metaDataType: 'Name',
                    questionBrand: 'Type in your answer here',
                    questionId: '48544604-dd1c-4523-9750-51477b005ce6',
                    questionTitle: 'Name',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Email',
                    questionBrand: 'Type in your answer here',
                    questionId: 'b735b6bb-02c4-4bcd-b05e-08b49a3ad0d3',
                    questionTitle: 'Email',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Phone',
                    questionBrand: 'Type in your answer here',
                    questionId: 'a40110bc-7517-4210-b527-f5b05556449a',
                    questionTitle: 'Phone',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Date',
                    questionBrand: 'Type in your answer here',
                    questionId: 'e5aeb990-ab8e-4c6c-94ef-3af456cec692',
                    questionTitle: 'Birthday',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Number',
                    questionBrand: 'Type in your answer here',
                    questionId: 'fdd0d327-ede1-41f8-8c00-50573408fcb8',
                    questionTitle: 'Value',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'String',
                    options: ['Male', 'Female'],
                    questionBrand: 'other',
                    questionId: '8dd4e758-4394-4be7-930f-e9749a92ce4c',
                    questionTitle: 'Gender',
                    scale: '0',
                    type: 'singleChoice',
                },
                {
                    mandatory: false,
                    metaDataType: 'String',
                    questionBrand: 'Type in your answer here',
                    questionId: '093453d0-791b-4afd-bc1a-c049768e548b',
                    questionTitle: 'Location',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: null,
                    options: [
                        'Staff/Service',
                        'Ambience',
                        'Food',
                        'Price',
                        'Cleanliness',
                    ],
                    questionBrand: 'other',
                    questionId: 'cf8c0262-c47c-48ee-9bde-f6291e0d8beb',
                    questionTitle:
                        'What Are The Things You Want Us To Improve?',
                    scale: '5',
                    type: 'multiChoice',
                },
            ],
        },
    ],
    rules: {},
    state: 'active',
    surveyEndDate: '2020-05-31 04:35:00',
    surveyId: 'ecef84c8-5787-4138-a8f2-318dcbd87b43',
    surveyName: 'Kiosk, anonymous, May 2020, metadata type question',
    surveyProperty: {
        image:
            'https://dt-program-banner.s3.us-west-1.amazonaws.com/e60c8719-30bf-4c89-9fcc-d27fc685ac65-65.png',
        hexCode: '#1ea188',
        fileName: 'logo.png',
        imageBase64: '',
    },
    surveyStartDate: '2020-05-06 04:35:30',
    surveyStatus: 'active',
    thankYouText: 'Thank you for taking our survey!',
    timezone: 'America/Los_Angeles',
    welcomeText: null,
}

/** @type {import('@dropthought/dropthought-data').Survey} */
export const multiPagesLogicSurvey = {
    anonymous: false,
    kiosk: 0,
    language: 'en',
    languages: ['en'],
    pageOrder: [
        '39c30b98-6ced-43e6-8be6-657c45e02d61',
        '150b0287-7a4d-42de-add3-257e73dda86e',
        'a915fe8d-e462-4509-be4f-0c4d187a4cd3',
        '3d88c5ff-f4ca-47c5-9b7b-2d74d3599076',
    ],
    pages: [
        {
            pageId: '39c30b98-6ced-43e6-8be6-657c45e02d61',
            pageTitle: 'Mandatory Questions',
            questions: [
                {
                    mandatory: false,
                    metaDataType: '',
                    options: ['Strongly Disagree', 'Strongly Agree'],
                    questionBrand: '',
                    questionId: 'e77e0660-5f5d-4929-a37d-25a9bffe9cde',
                    questionTitle: 'Rating Question 1 to 10',
                    scale: '10',
                    subType: 'slider',
                    type: 'rating',
                },
                {
                    mandatory: false,
                    metaDataType: '',
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: '8d3ed940-6549-4a0d-a79b-f13312f458b6',
                    questionTitle: 'Rating Question 1 to 5',
                    scale: '5',
                    subType: 'slider',
                    type: 'rating',
                },
                {
                    mandatory: true,
                    metaDataType: '',
                    options: ['Poor', 'Fair', 'Neutral', 'Good', 'Excellent'],
                    questionBrand: '',
                    questionId: 'ec6c98ba-1de0-4197-a2a1-d3db38bcf920',
                    questionTitle: 'Smiley Question 1 to 5',
                    scale: '5',
                    subType: 'smiley',
                    type: 'rating',
                },
            ],
        },
        {
            pageId: '150b0287-7a4d-42de-add3-257e73dda86e',
            pageTitle: 'Page 2',
            questions: [
                {
                    mandatory: false,
                    metaDataType: '',
                    questionBrand: 'Type in your answer here',
                    questionId: 'd2e0fb5e-f6ff-4c70-a68b-1ab8840c1268',
                    questionTitle: 'Open Question',
                    scale: '',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Name',
                    questionBrand: 'Type in your answer here',
                    questionId: 'b722df3d-1322-4d73-8a07-da366c7878b5',
                    questionTitle: 'Name',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Email',
                    questionBrand: 'eg. abc@test.com',
                    questionId: 'a2631061-fb8b-4bef-ac44-607005654254',
                    questionTitle: 'Email',
                    scale: '0',
                    type: 'open',
                },
                {
                    mandatory: false,
                    metaDataType: 'Date',
                    questionBrand: 'eg. 2010/01/08',
                    questionId: '29ee9a1e-5cd7-44ff-a330-9078c1a5417c',
                    questionTitle: 'Date',
                    scale: '0',
                    type: 'open',
                },
            ],
        },
        {
            pageId: 'a915fe8d-e462-4509-be4f-0c4d187a4cd3',
            pageTitle: 'Page 3',
            questions: [
                {
                    mandatory: false,
                    metaDataType: 'String',
                    options: ['Yes', 'No', 'OK'],
                    questionBrand: 'other',
                    questionId: 'cdf21afc-98ec-4980-95ad-7a03b6e6f427',
                    questionTitle: 'Single Response Question',
                    scale: '3',
                    type: 'singleChoice',
                },
                {
                    mandatory: false,
                    metaDataType: '',
                    options: [
                        'Rock music ',
                        'Pet armadillo',
                        'Twin 4-month-olds',
                        'Palm tree',
                    ],
                    questionBrand: 'other',
                    questionId: '34def0d5-d211-4314-8ace-cca90193208a',
                    questionTitle: 'Multiple Choice Question',
                    scale: '4',
                    type: 'multiChoice',
                },
            ],
        },
        {
            pageId: '3d88c5ff-f4ca-47c5-9b7b-2d74d3599076',
            pageTitle: 'Page 4',
            questions: [
                {
                    mandatory: true,
                    metaDataType: '',
                    options: ['Not at all Likely', 'Extremely Likely'],
                    questionBrand: '',
                    questionId: 'd6e338a6-8c8b-4f27-8e34-b0b7461094c8',
                    questionTitle:
                        'On a scale of 0 - 10, how likely are you to recommend us to your colleagues and friends?',
                    scale: '11',
                    subType: 'slider',
                    type: 'nps',
                },
                {
                    mandatory: true,
                    metaDataType: '',
                    options: ['Poor', 'Fair', 'Good'],
                    questionBrand: '',
                    questionId: '777ef5b3-1601-404f-8488-ad58aa4deccf',
                    questionTitle: 'Smiley 3',
                    scale: '3',
                    subType: 'smiley',
                    type: 'rating',
                },
                {
                    mandatory: true,
                    metaDataType: '',
                    options: ['Poor', 'Excellent'],
                    questionBrand: '',
                    questionId: 'c2f9d3f3-5cd1-4cbc-b99d-f0f5544806aa',
                    questionTitle: 'Smiley 2',
                    scale: '2',
                    subType: 'smiley',
                    type: 'rating',
                },
            ],
        },
    ],
    rules: {
        '39c30b98-6ced-43e6-8be6-657c45e02d61': [
            {
                id: '4bb2851f-d21b-46d7-ab17-b4ba08c34c07',
                toPageId: 'a915fe8d-e462-4509-be4f-0c4d187a4cd3',
                condition:
                    'e77e0660-5f5d-4929-a37d-25a9bffe9cde.answ.0||8d3ed940-6549-4a0d-a79b-f13312f458b6.answ.0||ec6c98ba-1de0-4197-a2a1-d3db38bcf920.answ.0',
                ruleIndex: 0,
                mode: 'noChange',
            },
            {
                id: 'b27be735-d96b-4aa7-b554-fbdcc19f3b38',
                toPageId: 'thank-you-page',
                condition:
                    'e77e0660-5f5d-4929-a37d-25a9bffe9cde.answ.0&&8d3ed940-6549-4a0d-a79b-f13312f458b6.answ.0&&ec6c98ba-1de0-4197-a2a1-d3db38bcf920.answ.0',
                ruleIndex: 1,
                mode: 'noChange',
            },
        ],
        '150b0287-7a4d-42de-add3-257e73dda86e': [
            {
                id: 'c2bbe5d2-e93c-413b-90bf-3fe2bf4439a9',
                toPageId: 'thank-you-page',
                condition: 'b722df3d-1322-4d73-8a07-da366c7878b5.nasr',
                ruleIndex: 0,
                mode: 'noChange',
            },
            {
                id: '9c98d572-9bca-40af-99a0-f2c1019961e2',
                toPageId: '3d88c5ff-f4ca-47c5-9b7b-2d74d3599076',
                condition: 'd2e0fb5e-f6ff-4c70-a68b-1ab8840c1268.nasr',
                ruleIndex: 1,
                mode: 'noChange',
            },
        ],
    },
    state: 'active',
    surveyEndDate: '2020-07-31 23:59:00',
    surveyId: '9d74ce7e-c69a-4c13-a028-68baa889c394',
    surveyName: '05/27, Skip Logic With Mixed Condition, 2020',
    surveyProperty: {
        image:
            'https://dt-program-banner.s3.us-west-1.amazonaws.com/e60c8719-30bf-4c89-9fcc-d27fc685ac65-65.png',
        hexCode: '#58b4ae',
        fileName: 'logo.png',
        imageBase64: '',
    },
    surveyStartDate: '2020-05-27 11:31:00',
    surveyStatus: 'active',
    thankYouText: 'A custom thank you message here',
    timezone: 'Asia/Taipei',
    welcomeText: 'This is a custom welcome message (optional)',
}
