default_platform(:ios)

platform :ios do
  desc "Increase build number"
  lane :IncreaseBuildNumberLane do
    increment_build_number()
  end
end

platform :ios do
  desc "Push a new release build to the App Center"
  lane :AppCenterLane do
    build_app(
        workspace: "iosDemoObjc.xcworkspace",
        scheme: "iosDemoObjc",
        clean: true,
        output_directory: "./",
        output_name: "iosDemoObjc.ipa",
        configuration: "Release",
        silent: true,
        export_method: "ad-hoc",
        export_options: {
            signingStyle: "manual",
            provisioningProfiles: {
                "com.bct.tpe.DTSDKDemo": "DTSDK-AdHoc"
            }
        }
    )

    appcenter_upload(
        api_token: "b6af699353ac1933b3b59a73fe8deac3326261d3",
        owner_name: "barney.chen-bahwancybertek.com",
        app_name: "Dropthought-SDK-Demo-iOS",
        notify_testers: true,
        ipa: "iosDemoObjc.ipa"
    )
  end
end